language: python
python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip3 install -r requirements.txt

script:
  # Download targeted them
  - make publish

after_failure:
  - make revert

deploy:
  provider: pages
  repo: JN-Blog/jn-blog.com
  target_branch: gh-pages
  skip_cleaneup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
