language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
script:
  # Download targeted them
  - make publish
after_failure:
  - make revert
deploy:
  provider: pages
  repo: JN-Blog/JN-Blog.github.io
  target_branch: master
  skip_cleaneup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: staging
