language: python
python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip3 install -r requirements.txt
  - pip3 install ghp-import

script:
  # Download targeted them
  - make publish github

deploy:
  provider: pages
  repo: JN-Blog/jn-blog.com
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
